In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
from sklearn import datasets
from sklearn.datasets import load_linnerud


In [3]:
linnerud = datasets.load_linnerud()
X = linnerud.data
y = linnerud.target
# show the first 5 rows
print(X[:5])
print(y[:5])

[[  5. 162.  60.]
 [  2. 110.  60.]
 [ 12. 101. 101.]
 [ 12. 105.  37.]
 [ 13. 155.  58.]]
[[191.  36.  50.]
 [189.  37.  52.]
 [193.  38.  58.]
 [162.  35.  62.]
 [189.  35.  46.]]
